### ISSUE TITLE
Apache role broken

### ISSUE THREAD

**Issue by lravindran** [vmware/chaperone#11]
Fails with the below message

failed: [chaperone-ui.corp.local] (item=[u'apache_packages']) => {
    "failed": true,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "install_recommends": null,
            "name": [
                "apache_packages"
            ],
            "only_upgrade": false,
            "package": [
                "apache_packages"
            ],
            "purge": false,
            "state": "present",
            "update_cache": false,
            "upgrade": null
        },
        "module_name": "apt"
    },
    "item": [
        "apache_packages"
    ],
    "msg": "No package matching 'apache_packages' is available"

**Comment by tdhite** [comment]
Do you still see errors? Would like to close that and recent changes (gerrit internal) should have fixed.

**Comment by tvuongp** [comment]
Will redeploy the CDS later today and validate. Thanks

Sent from my iPhone

On Jan 23, 2017, at 7:06 AM, Tom Hite <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you still see errors? Would like to close that and recent changes (gerrit internal) should have fixed.

-

**Comment by Penguin2600** [comment]
I still see this, what was the fix?

**Comment by tvuongp** [comment]
Apache fix was; (From Tom Scalan)
note for fix:  new version of ansible, all of apache_role, the "with_items" lines need to be updated for new version of ansible.  need to look like with_items: "{{ varname}} “

to avoid bare vars errors.  they aren't obvious


for work around, update the lines containing "with_items" to wrap the variable in "{{}}" so `with_items: apache_packages` becomes `with_items: "{{ apache_packages}}"`

there were a handful of them in the apache role

someone will fix that soonish


On Jan 25, 2017, at 1:42 PM, Charles V Bock <notifications@github.com<mailto:notifications@github.com>> wrote:


I still see this, what was the fix?

**Comment by Penguin2600** [comment]
Confirmed that was the fix.

Thank you sir.

**Comment by tompscanlan** [comment]
fixed by https://github.com/tomhite/ansible-role-apache/pull/2
