### ISSUE TITLE
Chaperone UI missing Apache

### ISSUE THREAD

**Issue by dnance** [vmware/chaperone#2]
Testcase:
When executing site.yml and not using chaperone as a router, router.yml and ui.yml host must be set to the same host or Apache server is not available to ui.  This causes the ui play to fail when trying to configure apache settings.

Error msg:
Destination directory /etc/apache2/sites-available does not exists

**Comment by tdhite** [comment]
Closing this here as it is really an issue belonging to ansible-playbooks-chaperone.
