### ISSUE TITLE
Was removal of these modules necessary

### ISSUE THREAD

**Issue by tompscanlan** [vmware/chaperone#28]
From commit 717bc7f90dc1818c6f780729b491935791fdc4ad from  @jdatx
* vcenter_datacenter
* add_nfs_datastore
* vio_create_network
* vio_add_ad_user
* os_create_user
* os_create_project
* does_vm_exist

**Comment by jdatx** [comment]
yes, modules where renamed to more appropriate names or deleted bc ansible now has native support for task or not needed
