### ISSUE TITLE
build-squid.eng.vmware.com not found

### ISSUE THREAD

**Issue by alexp789** [vmware/chaperone#4]
Hello, I might be missing something, however when attempting to follow the instructions and deploy chaperone-ui I'm hitting an issue downloading the depot files.  They are referencing "build-squid.eng.vmware.com" which isn't resolvable.

TASK [assets : get depot file stats] *******************************************
ok: [chaperone-ui.lab.vrandom.com]

TASK [assets : pull depot files for future downloads (may take many minutes)] **
fatal: [chaperone-ui.lab.vrandom.com]: FAILED! => {"changed": false, "dest": "/var/www/html/downloads/VMware-ESXi-6.0.0-2494585-depot.zip", "failed": true, "msg": "Request failed", "response": "Request failed: <urlopen error [Errno -2] Name or service not known>", "state": "absent", "status_code": -1, "url": "http://build-squid.eng.vmware.com/build/mts/release/bora-2494585/publish/VMware-ESXi-6.0.0-2494585-depot.zip"}

RUNNING HANDLER [iptables : restart ufw] ***************************************

PLAY RECAP *********************************************************************
chaperone-ui.lab.vrandom.com : ok=54   changed=13   unreachable=0    failed=1   

Thanks in advance

Alex

DNS resolution:
vmware@dev01:~/chaperone/ansible/playbooks/chaperone-ui$ dig build-squid.eng.vmware.com

; <<>> DiG 9.9.5-3ubuntu0.4-Ubuntu <<>> build-squid.eng.vmware.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 1757
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;build-squid.eng.vmware.com.	IN	A

;; AUTHORITY SECTION:
eng.vmware.com.		573	IN	SOA	ns1-sjc31.engx.vmware.com. si-admin.vmware.com. 2015122310 3600 900 2419200 900

;; Query time: 4 msec
;; SERVER: 10.30.20.20#53(10.30.20.20)
;; WHEN: Thu Jan 14 18:16:53 GMT 2016
;; MSG SIZE  rcvd: 115

**Comment by revolutionlabs** [comment]
Eh you're not missing anything, that squid proxy is only accessible inside VMware's corporate network. We will get it removed shortly.

**Comment by alexp789** [comment]
Thank you for the update, I did wonder! Is this software intended for public consumption? (I appreciate if this may be early days)
An update to the readme might be good to explain the situation? 
I'm going to have a look at provisioning the files locally, and if I get anywhere is a pull request appropriate with additional docs and instructions, or is this project not really in that place yet?

**Comment by bswrchrd** [comment]
Np, it's a VERY good question. Yes, the code is intended for public consumption however it's really in a high state of churn. Pull requests are definitely welcome! There should be some updates coming hopefully in the next week or so.

**Comment by alexp789** [comment]
Thanks for the feedback!  Just FYI the only package I couldn't find in the VMware download portal (I'm just pulling them together to try and get this running locally) is listed below (its only shipped as a .bundle, as far as I can tell):
http://build-squid.eng.vmware.com/build/mts/release/bora-2459827/publish/VMware-ovftool-4.1.0-2459827-lin.x86_64.zip

**Comment by tdhite** [comment]
All packages are just defaulted to vmware internal sites. They are all overridable by setting, in your playbooks, the variables listed here:

https://github.com/vmware/ansible-role-assets/blob/master/defaults/main.yml

No need for pull request, the assets role handles all downloads, just need to modify the pointers and hash codes to suit your needs locally.

**Comment by tdhite** [comment]
As a last comment, if you don't want to take the time to override the variables, you can also just download the assets listed, then place them on the CDS (deployment server) at: /var/www/html/downloads/. Future playbook runs will still check the hash codes, but since the files exist and the hash codes are correct (presuming your packages were correct), it will bypass attempts to download again. Check the https://github.com/vmware/ansible-role-assets role to see how that works.

Closing based on this and the last comment.
